version: "3"
services:
  db:
    image: postgres
    restart: always
    container_name: pgdb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
